import { Stream, ChatMessage } from "./types";

export const MOCK_STREAMS: Stream[] = [
  {
    id: "1",
    streamer: {
      id: "s1",
      username: "pixelcrafter",
      displayName: "PixelCrafter",
      avatarUrl: "/images/avatars/avatar_1.png",
      bio: "全栈开发者，热衷用 AI 构建工具，擅长前端和 AI 集成",
      followers: 15678,
    },
    project: {
      id: "p1",
      name: "NoteFlow",
      description: "AI 驱动的智能笔记应用，支持自动整理、知识图谱生成和语音输入实时转写",
      category: "notes",
      platforms: ["web", "mobile"],
      tags: ["AI", "笔记", "知识管理"],
      thumbnailUrl: "/images/thumbnails/project_1.png",
    },
    status: "live",
    codingTool: "cursor",
    viewers: 128,
    reactions: { want_to_use: 876, interesting: 1234, looking_forward: 543 },
    stages: [
      { name: "项目初始化", completed: true },
      { name: "UI 设计", completed: true },
      { name: "核心功能开发", completed: false },
      { name: "AI 集成", completed: false },
      { name: "部署上线", completed: false },
    ],
    startedAt: "2026-04-02T14:00:00Z",
    totalDevTime: 240,
  },
  {
    id: "2",
    streamer: {
      id: "s2",
      username: "vibe_queen",
      displayName: "Vibe Queen",
      avatarUrl: "/images/avatars/avatar_2.png",
      bio: "设计师转开发，用 AI 实现创意，专注交互设计和数据可视化",
      followers: 9876,
    },
    project: {
      id: "p2",
      name: "SnapMetrics",
      description: "社交媒体数据看板，一键生成营销报告，支持多平台数据聚合分析",
      category: "marketing",
      platforms: ["web"],
      tags: ["营销", "数据分析", "可视化"],
      thumbnailUrl: "/images/thumbnails/project_5.png",
    },
    status: "live",
    codingTool: "windsurf",
    viewers: 87,
    reactions: { want_to_use: 678, interesting: 321, looking_forward: 987 },
    stages: [
      { name: "需求分析", completed: true },
      { name: "数据接口", completed: true },
      { name: "图表组件", completed: true },
      { name: "报告生成", completed: false },
      { name: "用户测试", completed: false },
    ],
    startedAt: "2026-04-02T13:30:00Z",
    totalDevTime: 300,
  },
  {
    id: "3",
    streamer: {
      id: "s3",
      username: "code_wizard_42",
      displayName: "Code Wizard",
      avatarUrl: "/images/avatars/avatar_3.png",
      bio: "10 年后端经验，正在探索全栈 AI 开发，专注高性能系统",
      followers: 23456,
    },
    project: {
      id: "p3",
      name: "QuickCut",
      description: "AI 视频剪辑工具，自动识别精彩片段并生成短视频，支持多平台导出",
      category: "video",
      platforms: ["web", "desktop"],
      tags: ["视频", "AI 剪辑", "创作工具"],
      thumbnailUrl: "/images/thumbnails/project_8.png",
    },
    status: "live",
    codingTool: "claude-code",
    viewers: 65,
    reactions: { want_to_use: 777, interesting: 888, looking_forward: 999 },
    stages: [
      { name: "架构设计", completed: true },
      { name: "视频上传", completed: true },
      { name: "AI 分析引擎", completed: true },
      { name: "剪辑界面", completed: false },
      { name: "导出功能", completed: false },
    ],
    startedAt: "2026-04-02T12:00:00Z",
    totalDevTime: 540,
  },
  {
    id: "4",
    streamer: {
      id: "s4",
      username: "indie_hacker",
      displayName: "独立开发者小明",
      avatarUrl: "/images/avatars/avatar_4.png",
      bio: "连续创业者，用 Vibe Coding 快速验证想法，已上线 3 个产品",
      followers: 7654,
    },
    project: {
      id: "p4",
      name: "TaskForge",
      description: "游戏化任务管理器，把待办事项变成 RPG 冒险，完成任务获得经验值和装备",
      category: "productivity",
      platforms: ["mobile"],
      tags: ["效率", "游戏化", "任务管理"],
      thumbnailUrl: "/images/thumbnails/project_12.png",
    },
    status: "away",
    codingTool: "bolt",
    viewers: 35,
    reactions: { want_to_use: 555, interesting: 222, looking_forward: 111 },
    stages: [
      { name: "原型设计", completed: true },
      { name: "角色系统", completed: true },
      { name: "任务引擎", completed: false },
      { name: "成就系统", completed: false },
    ],
    startedAt: "2026-04-02T10:00:00Z",
    totalDevTime: 480,
  },
  {
    id: "5",
    streamer: {
      id: "s5",
      username: "ai_artisan",
      displayName: "AI Artisan",
      avatarUrl: "/images/avatars/avatar_5.png",
      bio: "AI 产品设计师，专注用户体验和多语言交互设计",
      followers: 18765,
    },
    project: {
      id: "p5",
      name: "LangBridge",
      description: "实时翻译通讯应用，支持 30+ 语言无缝对话，AI 自动适配语境",
      category: "social",
      platforms: ["web", "mobile"],
      tags: ["翻译", "实时通讯", "多语言"],
      thumbnailUrl: "/images/thumbnails/project_6.png",
    },
    status: "live",
    codingTool: "copilot",
    viewers: 95,
    reactions: { want_to_use: 765, interesting: 432, looking_forward: 876 },
    stages: [
      { name: "通信协议", completed: true },
      { name: "翻译引擎", completed: true },
      { name: "聊天界面", completed: true },
      { name: "语音翻译", completed: false },
    ],
    startedAt: "2026-04-02T15:00:00Z",
    totalDevTime: 360,
  },
  {
    id: "6",
    streamer: {
      id: "s6",
      username: "dev_sensei",
      displayName: "Dev Sensei",
      avatarUrl: "/images/avatars/avatar_6.png",
      bio: "全栈导师，直播教学 AI 编程，累计帮助 5000+ 学员入门",
      followers: 32109,
    },
    project: {
      id: "p6",
      name: "CodeQuest",
      description: "交互式编程学习平台，AI 生成个性化编程挑战，支持实时代码沙箱",
      category: "education",
      platforms: ["web"],
      tags: ["教育", "编程学习", "AI 教学"],
      thumbnailUrl: "/images/thumbnails/project_2.png",
      productUrl: "https://codequest.example.com",
    },
    status: "offline",
    codingTool: "cursor",
    viewers: 0,
    reactions: { want_to_use: 850, interesting: 250, looking_forward: 350 },
    stages: [
      { name: "课程体系", completed: true },
      { name: "代码沙箱", completed: true },
      { name: "AI 出题引擎", completed: true },
      { name: "排行榜", completed: true },
      { name: "社区功能", completed: true },
    ],
    startedAt: "2026-04-01T09:00:00Z",
    totalDevTime: 720,
  },
  {
    id: "7",
    streamer: {
      id: "s7",
      username: "neural_nomad",
      displayName: "Neural Nomad",
      avatarUrl: "/images/avatars/avatar_7.png",
      bio: "探索神经网络的奥秘，从理论到实践，构建智能应用",
      followers: 11223,
    },
    project: {
      id: "p7",
      name: "ReviewBot",
      description: "自动化代码审查助手，利用 AI 分析代码库，提供审查建议和潜在 Bug 检测",
      category: "dev-tools",
      platforms: ["api", "extension"],
      tags: ["AI", "代码审查", "DevOps"],
      thumbnailUrl: "/images/thumbnails/project_7.png",
    },
    status: "live",
    codingTool: "copilot",
    viewers: 42,
    reactions: { want_to_use: 999, interesting: 101, looking_forward: 202 },
    stages: [
      { name: "架构设计", completed: true },
      { name: "解析引擎", completed: true },
      { name: "AI 审查逻辑", completed: true },
      { name: "VS Code 插件", completed: false },
      { name: "CI/CD 集成", completed: false },
    ],
    startedAt: "2026-04-02T11:00:00Z",
    totalDevTime: 420,
  },
  {
    id: "8",
    streamer: {
      id: "s8",
      username: "quantum_quill",
      displayName: "Quantum Quill",
      avatarUrl: "/images/avatars/avatar_8.png",
      bio: "用 AI 赋能科学计算和数据可视化，让复杂数据变得简单易懂",
      followers: 6789,
    },
    project: {
      id: "p8",
      name: "FitPulse",
      description: "AI 个性化健身计划应用，根据健康数据定制锻炼方案，提供动作指导",
      category: "other",
      platforms: ["mobile"],
      tags: ["健康", "AI", "健身"],
      thumbnailUrl: "/images/thumbnails/project_4.png",
    },
    status: "offline",
    codingTool: "replit",
    viewers: 0,
    reactions: { want_to_use: 600, interesting: 300, looking_forward: 150 },
    stages: [
      { name: "需求调研", completed: true },
      { name: "UI 原型", completed: true },
      { name: "训练算法", completed: true },
      { name: "动作识别", completed: true },
      { name: "上线发布", completed: true },
    ],
    startedAt: "2026-03-28T09:00:00Z",
    totalDevTime: 600,
  },
  {
    id: "9",
    streamer: {
      id: "s1",
      username: "pixelcrafter",
      displayName: "PixelCrafter",
      avatarUrl: "/images/avatars/avatar_1.png",
      bio: "全栈开发者，热衷用 AI 构建工具，擅长前端和 AI 集成",
      followers: 15678,
    },
    project: {
      id: "p9",
      name: "CashFlow AI",
      description: "AI 智能支出追踪器，通过分析消费习惯提供个性化预算建议和节省开支洞察",
      category: "other",
      platforms: ["mobile", "web"],
      tags: ["金融", "AI", "预算管理"],
      thumbnailUrl: "/images/thumbnails/project_9.png",
    },
    status: "offline",
    codingTool: "cursor",
    viewers: 0,
    reactions: { want_to_use: 412, interesting: 634, looking_forward: 289 },
    stages: [
      { name: "数据模型", completed: true },
      { name: "消费分析", completed: true },
      { name: "预算引擎", completed: false },
      { name: "报告生成", completed: false },
    ],
    startedAt: "2026-03-30T10:00:00Z",
    totalDevTime: 200,
  },
  {
    id: "10",
    streamer: {
      id: "s3",
      username: "code_wizard_42",
      displayName: "Code Wizard",
      avatarUrl: "/images/avatars/avatar_3.png",
      bio: "10 年后端经验，正在探索全栈 AI 开发，专注高性能系统",
      followers: 23456,
    },
    project: {
      id: "p10",
      name: "SocialPilot",
      description: "AI 社交媒体调度工具，自动生成内容并优化发布策略，提升互动率",
      category: "marketing",
      platforms: ["web"],
      tags: ["社交", "营销", "自动化"],
      thumbnailUrl: "/images/thumbnails/project_10.png",
      productUrl: "https://socialpilot.example.com",
    },
    status: "offline",
    codingTool: "v0",
    viewers: 0,
    reactions: { want_to_use: 580, interesting: 450, looking_forward: 230 },
    stages: [
      { name: "平台接入", completed: true },
      { name: "内容生成", completed: true },
      { name: "调度引擎", completed: true },
      { name: "数据面板", completed: true },
      { name: "用户系统", completed: true },
    ],
    startedAt: "2026-03-25T14:00:00Z",
    totalDevTime: 510,
  },
  {
    id: "11",
    streamer: {
      id: "s5",
      username: "ai_artisan",
      displayName: "AI Artisan",
      avatarUrl: "/images/avatars/avatar_5.png",
      bio: "AI 产品设计师，专注用户体验和多语言交互设计",
      followers: 18765,
    },
    project: {
      id: "p11",
      name: "MindMap AI",
      description: "AI 协作笔记与思维导图工具，自动整理笔记、提炼关键信息并提供扩展建议",
      category: "notes",
      platforms: ["web", "desktop"],
      tags: ["协作", "AI", "思维导图"],
      thumbnailUrl: "/images/thumbnails/project_11.png",
      productUrl: "https://mindmap-ai.example.com",
    },
    status: "offline",
    codingTool: "windsurf",
    viewers: 0,
    reactions: { want_to_use: 891, interesting: 123, looking_forward: 456 },
    stages: [
      { name: "核心编辑器", completed: true },
      { name: "AI 整理引擎", completed: true },
      { name: "实时协作", completed: true },
      { name: "导出分享", completed: true },
      { name: "移动适配", completed: true },
    ],
    startedAt: "2026-03-20T08:00:00Z",
    totalDevTime: 400,
  },
  {
    id: "12",
    streamer: {
      id: "s4",
      username: "indie_hacker",
      displayName: "独立开发者小明",
      avatarUrl: "/images/avatars/avatar_4.png",
      bio: "连续创业者，用 Vibe Coding 快速验证想法，已上线 3 个产品",
      followers: 7654,
    },
    project: {
      id: "p12",
      name: "PixelQuest",
      description: "像素风格的 Roguelike 小游戏，AI 自动生成地图和怪物，每次冒险都不同",
      category: "gaming",
      platforms: ["web", "mobile"],
      tags: ["游戏", "像素风", "Roguelike"],
      thumbnailUrl: "/images/thumbnails/project_3.png",
    },
    status: "away",
    codingTool: "bolt",
    viewers: 19,
    reactions: { want_to_use: 345, interesting: 789, looking_forward: 210 },
    stages: [
      { name: "游戏引擎", completed: true },
      { name: "地图生成", completed: true },
      { name: "战斗系统", completed: false },
      { name: "道具商店", completed: false },
    ],
    startedAt: "2026-04-02T09:00:00Z",
    totalDevTime: 350,
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: "m1",
    userId: "u1",
    username: "观众小李",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "来了来了",
    timestamp: "2026-04-02T14:30:12Z",
  },
  {
    id: "m2",
    userId: "u2",
    username: "CodeFan99",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "前排占座",
    timestamp: "2026-04-02T14:30:15Z",
  },
  {
    id: "m3",
    userId: "u3",
    username: "路过的产品汪",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "今天做什么项目？",
    timestamp: "2026-04-02T14:30:28Z",
  },
  {
    id: "m4",
    userId: "u4",
    username: "TechNerd",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "看上一场说要做个待办应用",
    timestamp: "2026-04-02T14:30:35Z",
  },
  {
    id: "m5",
    userId: "u3",
    username: "路过的产品汪",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "又是待办 app 哈哈哈 程序员最爱造的轮子",
    timestamp: "2026-04-02T14:30:42Z",
  },
  {
    id: "m6",
    userId: "u5",
    username: "设计狮大卫",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "等下 这配色方案是 AI 选的？",
    timestamp: "2026-04-02T14:31:55Z",
  },
  {
    id: "m7",
    userId: "u1",
    username: "观众小李",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "感觉是 shadcn 的默认主题吧",
    timestamp: "2026-04-02T14:32:03Z",
  },
  {
    id: "m8",
    userId: "u5",
    username: "设计狮大卫",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "哦确实，那个圆角和间距一看就是",
    timestamp: "2026-04-02T14:32:18Z",
  },
  {
    id: "m9",
    userId: "u6",
    username: "react_master",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "等等 那个 useEffect 的依赖数组是空的没问题吗",
    timestamp: "2026-04-02T14:33:41Z",
  },
  {
    id: "m10",
    userId: "u4",
    username: "TechNerd",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "应该要加 [id] 吧",
    timestamp: "2026-04-02T14:33:52Z",
  },
  {
    id: "m11",
    userId: "u6",
    username: "react_master",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "对 不然切换页面不会重新请求",
    timestamp: "2026-04-02T14:34:01Z",
  },
  {
    id: "m12",
    userId: "u7",
    username: "vibe_coder",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "666",
    timestamp: "2026-04-02T14:34:45Z",
  },
  {
    id: "m13",
    userId: "u2",
    username: "CodeFan99",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "一整个表单直接生成出来了 这也太快了",
    timestamp: "2026-04-02T14:34:48Z",
  },
  {
    id: "m14",
    userId: "u8",
    username: "fullstack_fan",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "请问用的是 Cursor 还是 Copilot",
    timestamp: "2026-04-02T14:35:22Z",
  },
  {
    id: "m15",
    userId: "u4",
    username: "TechNerd",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "标题写了用 Cursor 的",
    timestamp: "2026-04-02T14:35:30Z",
  },
  {
    id: "m16",
    userId: "u8",
    username: "fullstack_fan",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "没注意 谢谢",
    timestamp: "2026-04-02T14:35:38Z",
  },
  {
    id: "m17",
    userId: "u9",
    username: "新手小白",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "小白问一下 这个 Supabase 是免费的吗",
    timestamp: "2026-04-02T14:36:15Z",
  },
  {
    id: "m18",
    userId: "u2",
    username: "CodeFan99",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "有免费额度 个人项目够用",
    timestamp: "2026-04-02T14:36:28Z",
  },
  {
    id: "m19",
    userId: "u3",
    username: "路过的产品汪",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "这loading动画有点丑 能不能换个骨架屏",
    timestamp: "2026-04-02T14:37:50Z",
  },
  {
    id: "m20",
    userId: "u5",
    username: "设计狮大卫",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "+1 骨架屏体验好很多",
    timestamp: "2026-04-02T14:37:58Z",
  },
  {
    id: "m21",
    userId: "u1",
    username: "观众小李",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "hhhh 弹幕变成代码审查现场了",
    timestamp: "2026-04-02T14:38:05Z",
  },
  {
    id: "m22",
    userId: "u7",
    username: "vibe_coder",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "主播心态要好 被弹幕审代码",
    timestamp: "2026-04-02T14:38:12Z",
  },
  {
    id: "m23",
    userId: "u10",
    username: "startup_builder",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "说真的这种一边看一边学的方式比教程效率高",
    timestamp: "2026-04-02T14:39:30Z",
  },
  {
    id: "m24",
    userId: "u6",
    username: "react_master",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "嗯 能看到实际开发中怎么处理边界情况",
    timestamp: "2026-04-02T14:39:45Z",
  },
  {
    id: "m25",
    userId: "u11",
    username: "debug_master",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "报错了报错了 控制台一片红",
    timestamp: "2026-04-02T14:40:20Z",
  },
  {
    id: "m26",
    userId: "u7",
    username: "vibe_coder",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "经典 cannot read properties of undefined",
    timestamp: "2026-04-02T14:40:25Z",
  },
  {
    id: "m27",
    userId: "u4",
    username: "TechNerd",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "optional chaining 加一下就好了",
    timestamp: "2026-04-02T14:40:33Z",
  },
  {
    id: "m28",
    userId: "u1",
    username: "观众小李",
    avatarUrl: "/images/avatars/avatar_default.png",
    content: "加油加油",
    timestamp: "2026-04-02T14:41:00Z",
  },
];
